batch: 16
box: 7.5
cls: 0.5
copy_paste: 0.0
data: yolo_dataset\dataset.yaml
degrees: 0.0
device: auto
dfl: 1.5
epochs: 100
exist_ok: true
fliplr: 0.5
flipud: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 1000
lr0: 0.001
lrf: 0.01
mixup: 0.0
model: yolo11n.pt
momentum: 0.937
mosaic: 1.0
name: car_damage_yolo11n
optimizer: AdamW
perspective: 0.0
pretrained: true
project: runs/detect
scale: 0.5
shear: 0.0
translate: 0.1
warmup_epochs: 3
weight_decay: 0.0005
